language: node_js
node_js:
    - "7.0"
script:
    - echo "Deploying!"
install:
    - npm install -g firebase-tools
after_success:
    - firebase deploy --project fir-signinproject-d8d84 --token $FIREBASE_TOKEN
